const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const LEGAL=[
'ADOSH-SF CoP 2.0 - Personal Protective Equipment','ADOSH-SF CoP 3.0 - Occupational Noise','ADOSH-SF CoP 8.0 - General Workplace Amenities','ADOSH-SF CoP 15.0 - Electrical Safety','ADOSH-SF CoP 17.0 - Safety Signage and Signals','ADOSH-SF CoP 21.0 - Permit to Work Systems','ADOSH-SF CoP 22.0 - Barricading of Hazards','ADOSH-SF CoP 23.0 - Working at Heights','ADOSH-SF CoP 26.0 - Scaffolding','ADOSH-SF CoP 28.0 - Hot Work Operations','ADOSH-SF CoP 29.0 - Excavation Work','ADOSH-SF CoP 33.0 - Working On or Adjacent to a Road','ADOSH-SF CoP 34.0 - Safe Use of Lifting Equipment and Lifting Accessories','ADOSH-SF CoP 35.0 - Portable Power Tools','ADOSH-SF CoP 36.0 - Plant and Equipment','ADOSH-SF CoP 37.0 - Ladders','ADOSH-SF CoP 42.0 - Pre Cast Construction','ADOSH-SF CoP 43.0 - Temporary Structures','ADOSH-SF CoP 44.0 - Traffic Management and Logistics','ADOSH-SF CoP 53.0 - OSH Management During Construction Work','ADOSH-SF CoP 53.1 - OSH Construction Management Plan','ADOSH-SF CoP 54.0 - Waste Management','ADCD 2018 Fire & Life Safety Code of Practice','Aldar OSH MS Rev-08','Project Approved OSH Plan','OSH Construction Management Plan','MSRA'];
const PRESETS={
'Access and Egress':{root:'Poor planning / Poor supervision',desc:['It was observed that villa access and egress routes were obstructed by construction materials, debris, cables and temporary works, affecting safe movement and emergency access.','It was evident that unsafe access arrangements such as single planks, poorly maintained access bridges or damaged temporary steps were being used to reach villas, excavations or workstations.','Lack of dedicated, demarcated and inspected pedestrian access was observed, creating slip, trip and fall hazards.'],imm:['Unsafe access routes were restricted immediately and workers were redirected to safer access points until rectification was completed.','The responsible engineer and supervision team were instructed to remove obstructions and restore safe access without delay.','Work was held at the affected location where safe access and egress could not be ensured.'],act:['All unsafe and substandard access arrangements shall be removed immediately and replaced with safe access bridges, ramps, stairs or platforms in line with approved design and project requirements.','All access and egress routes shall be kept clear of materials, cables, debris and protruding steel at all times.','A dedicated team shall be appointed for access bridge installation, inspection and routine maintenance.','Access routes shall be clearly demarcated, provided with suitable signage and inspected by competent supervision on a daily basis.','The permit-to-work approval shall include physical verification of safe access and housekeeping conditions prior to allowing work to proceed.','The workforce and supervisors shall be briefed on the importance of maintaining safe access and emergency egress arrangements.'],legal:['ADOSH-SF CoP 8.0 - General Workplace Amenities','ADOSH-SF CoP 22.0 - Barricading of Hazards','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA']},
'Permit to Work':{root:'PTW system failure / Lack of field verification',desc:['It was observed that critical activities were being carried out without a valid permit to work or without adequate physical verification of the work location.','Permits were issued, signed or approved without confirming actual site conditions, supervision, access, isolation and required control measures.','The PTW document did not adequately identify the hazards and controls present at the work front.'],imm:['The affected activity was stopped immediately and the permit was placed on hold pending full site verification.','The permit issuer, area engineer, HSE team and responsible supervisor were called to the location to review the PTW status and actual work conditions.','Work was not allowed to resume until the permit conditions, supervision and control measures were physically verified.'],act:['All activities found outside PTW control shall be immediately suspended until a valid permit is issued and approved by authorised personnel after physical site verification.','The PTW system shall remain under the control of the main contractor, and permits shall not be signed or authorised without field verification.','All incomplete, incorrectly drafted or non-compliant PTWs shall be cancelled and revalidated only after required controls are implemented.','The roles and responsibilities of permit issuer, receiver, approver and verifier shall be clearly communicated to engineers, supervisors and HSE personnel.','PTW audits shall be conducted routinely to verify permit quality, site control implementation and closeout evidence.','Repeated PTW non-compliance shall be escalated to project management and enforcement action shall be taken against responsible personnel.'],legal:['ADOSH-SF CoP 21.0 - Permit to Work Systems','ADOSH-SF CoP 53.0 - OSH Management During Construction Work','Aldar OSH MS Rev-08','Project Approved OSH Plan','OSH Construction Management Plan','MSRA']},
'Work at Height':{root:'Poor supervision / PTW failure / Planning failure',desc:['Operatives were observed working at height near leading edges, rooftops or elevated platforms without adequate fall prevention arrangements.','Ladders were being used as working platforms for activities where proper scaffold, mobile tower or working platform was required.','Work at height activities were being carried out without adequate PTW control, safe access, competent supervision or full body harness anchorage where required.'],imm:['All unsafe work at height activities were stopped immediately and workers were removed from the elevated work area.','The affected area was isolated and access below the work at height activity was restricted to control falling object exposure.','The responsible supervision team was instructed to verify working platform, edge protection, PTW and PPE requirements before restart.'],act:['All work at height activities shall be suspended where adequate safe access, working platform, fall prevention or PTW controls are not in place.','Suitable working platforms such as compliant scaffolds, mobile towers or MEWPs shall be provided; ladders shall not be used as working platforms.','Full body harnesses with suitable anchorage shall be used where fall prevention is not fully achieved by collective protection.','The work area shall be inspected by competent supervision prior to work and continuously monitored during the activity.','Workers and supervisors shall receive task-specific WAH training, toolbox talks and awareness on stop-work requirements.','No rooftop or leading edge activity shall proceed without formal authorisation, PTW approval and physical verification by competent supervision.'],legal:['ADOSH-SF CoP 23.0 - Working at Heights','ADOSH-SF CoP 21.0 - Permit to Work Systems','ADOSH-SF CoP 26.0 - Scaffolding','ADOSH-SF CoP 37.0 - Ladders','Aldar OSH MS Rev-08','Project Approved OSH Plan']},
'Scaffolding':{root:'Inspection failure / Inadequate competence',desc:['Scaffolding was observed in unsafe condition, including missing components, unsecured planks, improper access ladders, missing toe boards, lack of outriggers, unstable alignment or unauthorised modification.','Mobile or aluminium scaffolds were used without compliance with manufacturer requirements, approved design or valid inspection/tagging controls.','Red-tagged or partially erected scaffolds were observed being used for work activities.'],imm:['Unsafe scaffold use was stopped immediately and the scaffold was restricted from use until rectified and inspected by a competent person.','The green tag was instructed to be removed where scaffolding was not compliant, and the scaffold was placed under red-tag control.','Workers were removed from the unsafe scaffold arrangement and the area was controlled to prevent unauthorised access.'],act:['All non-compliant scaffolds shall be taken out of service immediately and shall not be used until fully rectified and inspected.','Scaffolds shall be erected, modified and dismantled only by competent scaffolders in accordance with the approved design and manufacturer instructions.','All required components including guardrails, mid rails, toe boards, bracing, base plates, outriggers, access ladders and locking pins shall be installed before use.','Unauthorised scaffold modifications and loose plank arrangements shall be removed immediately.','A competent scaffolding inspector shall inspect and tag scaffolds after erection, modification, adverse weather or any condition affecting stability.','Routine scaffold inspections shall be tracked, and repeated non-compliances shall be escalated to management.'],legal:['ADOSH-SF CoP 26.0 - Scaffolding','ADOSH-SF CoP 23.0 - Working at Heights','ADOSH-SF CoP 37.0 - Ladders','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA']},
'Excavation':{root:'Poor planning / Inadequate barricading',desc:['Boundary wall, MEP or service excavations were found without hard barricades, warning signs, safe access or adequate edge protection.','Materials, blocks or debris were stored close to excavation edges, creating risk of collapse, falling materials and instability.','Excavation work was observed without adequate PTW control, competent supervision or daily inspection records.'],imm:['Unsafe excavation activity was stopped immediately and access to the excavation edge was restricted.','The responsible engineer and HSE team were instructed to provide hard barricades, warning signage and safe access arrangements without delay.','Materials near the excavation edge were instructed to be removed to maintain safe setback distance.'],act:['All excavation areas shall be protected with rigid barricades or approved hard barriers, warning signs and safe access/egress arrangements.','Materials, blocks, equipment and spoil shall be kept away from excavation edges to maintain safe setback distance and prevent collapse.','Excavation PTW shall be implemented and verified before starting work, including competent person inspection and required protective measures.','Open excavations near villa access, pedestrian routes and live roads shall be clearly demarcated and inspected daily.','Where required, benching, sloping, shoring or other engineered controls shall be implemented in line with approved MSRA.','Supervision teams shall conduct continuous monitoring and brief the workforce on excavation hazards.'],legal:['ADOSH-SF CoP 29.0 - Excavation Work','ADOSH-SF CoP 22.0 - Barricading of Hazards','ADOSH-SF CoP 21.0 - Permit to Work Systems','ADOSH-SF CoP 17.0 - Safety Signage and Signals','Aldar OSH MS Rev-08','Project Approved OSH Plan']},
'Barricading Hazards / Floor Openings':{root:'Poor maintenance / Inspection failure',desc:['Floor openings, manholes, stair landings, roof edges, temporary structures or excavation edges were not adequately protected, barricaded or covered.','Barricades were found slanted, incomplete, removed or not maintained, and protruding rebars were not protected.','Unsuitable materials such as thin plywood or temporary covers were used to cover openings, creating fall, trip and falling object hazards.'],imm:['Access to the affected hazard area was restricted immediately and temporary control measures were implemented.','The responsible team was instructed to reinstate suitable barricading, covers, toe boards and signage without delay.','Workers were prevented from entering the unsafe area until the barricading and opening protection were verified.'],act:['All floor openings, manholes, leading edges, stair openings and excavation edges shall be protected using rigid barricades, suitable covers or guardrail systems as applicable.','Covers shall be secured, load-bearing and clearly identified; unsuitable materials shall be removed immediately.','Protruding rebars shall be removed where possible or protected with mushroom-type rebar caps.','Toe boards and handrails shall be reinstated where missing, and barricades shall be installed as per design and legal requirements.','A dedicated maintenance team shall inspect and maintain barricades continuously, especially near live roads, pedestrian routes and workstations.','Routine inspections shall be recorded, and repeated removal of barricades shall be escalated for enforcement action.'],legal:['ADOSH-SF CoP 22.0 - Barricading of Hazards','ADOSH-SF CoP 23.0 - Working at Heights','ADOSH-SF CoP 17.0 - Safety Signage and Signals','Aldar OSH MS Rev-08','Project Approved OSH Plan']},
'Edge Protection':{root:'Poor supervision / Poor maintenance',desc:['Edge protection was missing, incomplete, improperly anchored or not securely fixed at leading edges, windows, roofs, lift shafts or access areas.','Toe boards were missing above access areas, creating risk of falling materials from height.','Makeshift edge protection arrangements were observed and did not meet legal or project requirements.'],imm:['Unsafe work near exposed leading edges was stopped immediately and access to the affected area was restricted.','The responsible area engineer and supervision team were called to the location and instructed to rectify the unsafe condition.','The affected area was isolated and workers were stopped from accessing exposed edges until protection was verified.'],act:['All activities near unprotected leading edges shall be suspended until adequate edge protection is installed and verified.','Edge protection shall include complete guardrail systems with top rails, mid rails and toe boards in accordance with legal and project requirements.','All edge protection systems shall be properly anchored, aligned and secured to prevent displacement during use.','All missing, loose or damaged sections shall be reinstated immediately to maintain continuous protection.','A comprehensive inspection of all edge protection across the work area shall be carried out by site supervision and OSH team.','Edge protection shall not be removed until all roof, MEP and related activities are fully completed and safe conditions are confirmed.'],legal:['ADOSH-SF CoP 23.0 - Working at Heights','ADOSH-SF CoP 22.0 - Barricading of Hazards','ADOSH-SF CoP 2.0 - Personal Protective Equipment','Aldar OSH MS Rev-08','Project Approved OSH Plan']},
'Electrical Safety / Portable Tools':{root:'Inspection failure / Inadequate maintenance',desc:['Temporary electrical arrangements, DBs, generators, cables or portable tools were observed with poor earthing, damaged cables, poor cable management, missing inspections or unsafe power tapping.','Live or flexible cables were routed across roads, access routes, wet areas or metal surfaces without adequate protection.','PAT requirements, colour coding, DB inspection stickers or earth pit inspection details were missing or not maintained.'],imm:['Unsafe electrical equipment and defective tools were removed from use immediately and the affected system was isolated where required.','A competent electrical team was instructed to inspect DBs, generators, cables, earthing and tools before further use.','Workers were kept away from unsafe electrical arrangements until rectification and verification were completed.'],act:['A dedicated competent electrical team shall be appointed for inspection, installation and maintenance of temporary electrical arrangements.','All DBs, generators, cables and portable tools shall be inspected, tagged, colour coded and maintained with records.','Earthing arrangements shall be provided and verified for generators, DBs and tower lights, including earth pit identification and next inspection details.','Damaged cables, defective sockets, poor cable routing and unauthorised power tapping shall be removed or rectified immediately.','Cables shall be routed using insulated hooks, poles, encasement or other suitable protection to prevent mechanical damage and trip hazards.','The workforce shall be trained on safe cable management and portable tool safety requirements.'],legal:['ADOSH-SF CoP 15.0 - Electrical Safety','ADOSH-SF CoP 35.0 - Portable Power Tools','ADOSH-SF CoP 36.0 - Plant and Equipment','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA']},
'Plant and Equipment':{root:'Poor inspection / Inadequate maintenance',desc:['Plant or equipment was observed in unsafe condition, including damaged wheels, defective fittings, missing fire extinguishers, poor cabin housekeeping, inadequate first aid boxes or unsafe modifications.','MEWPs or manlifts were observed being operated on uneven or unstable surfaces, creating risk of overturning and serious injury.','Equipment inspection stickers, emergency arrangements or safety controls were missing or not properly maintained.'],imm:['Unsafe plant or equipment was stopped immediately and removed from operation pending inspection by a competent person.','The responsible plant team and supervision were instructed to rectify defects and verify certification before further use.','Operators were instructed not to operate defective or unstable equipment until all safety controls were restored.'],act:['All plant and equipment shall be inspected by competent personnel before use and shall not operate with defects affecting safety.','Defective equipment, damaged accessories or unsafe modifications shall be removed from service immediately.','MEWPs and mobile plant shall operate only on firm, level and suitable ground with required emergency arrangements active.','Fire extinguishers, first aid boxes, cabin housekeeping, operator visibility and emergency controls shall be maintained.','Inspection records, third-party certificates and pre-use checklists shall be available and verified routinely.','Operators, supervisors and maintenance teams shall receive training on equipment safety and defect reporting requirements.'],legal:['ADOSH-SF CoP 36.0 - Plant and Equipment','ADOSH-SF CoP 34.0 - Safe Use of Lifting Equipment and Lifting Accessories','ADOSH-SF CoP 44.0 - Traffic Management and Logistics','Aldar OSH MS Rev-08','Project Approved OSH Plan']},
'Material Storage / Fire Protection':{root:'Poor housekeeping / Fire risk controls not implemented',desc:['Materials, joinery, glass panels, chemicals or combustible items were stored in villas or storage areas without adequate segregation, access control, firefighting arrangements or protection.','Materials were over-stacked, stored near excavations, stored above sprinkler height or placed in undesignated areas affecting access and fire safety.','Fire extinguishers, hose reels, smoke detectors, labels, Civil Defence approvals or fire warden arrangements were missing or inadequate.'],imm:['Unsafe storage conditions were controlled immediately and responsible teams were instructed to relocate, segregate or secure materials.','Fire protection deficiencies were communicated to the contractor for immediate rectification, including provision or replacement of firefighting equipment.','Access to unsafe storage areas was restricted until adequate control measures were implemented.'],act:['All materials shall be stored only in designated, approved and demarcated storage areas with safe access and emergency access maintained.','Combustible materials, chemicals and glass panels shall be properly segregated, labelled, protected and secured to prevent fire, collapse or injury.','Fire risk assessment shall be conducted for storage areas and adequate firefighting arrangements shall be provided and maintained.','Materials shall not be stored above sprinkler height or in a manner that blocks access, emergency routes or firefighting systems.','Dedicated fire wardens shall be appointed to conduct routine inspections of storage areas.','Civil Defence approvals, store layouts, emergency contacts, spill kits and required fire safety documentation shall be maintained where applicable.'],legal:['ADCD 2018 Fire & Life Safety Code of Practice','ADOSH-SF CoP 8.0 - General Workplace Amenities','ADOSH-SF CoP 54.0 - Waste Management','ADOSH-SF CoP 44.0 - Traffic Management and Logistics','Aldar OSH MS Rev-08','Project Approved OSH Plan']},
'Traffic / Logistics / Precast':{root:'Poor logistics planning / Lack of control',desc:['Traffic and logistics arrangements were inadequate, including poor pedestrian segregation, missing flagman/banksman control, unsafe reversing or A-frame trailer load securing deficiencies.','Precast elements or materials were transported, loaded, unloaded or stored without adequate securing, exclusion zones or safe traffic interface controls.','Vehicles and plant movements were not adequately controlled near live roads, pedestrian routes or active work fronts.'],imm:['Unsafe vehicle or logistics movement was stopped immediately and the affected route was controlled.','Banksman/flagman control, exclusion zones and pedestrian segregation were instructed to be provided before further movement.','The responsible logistics team was called to review and correct the traffic interface arrangement.'],act:['A traffic and logistics plan shall be implemented and maintained, including pedestrian segregation, signage, speed control, illumination and banksman arrangements.','A-frame trailers and precast elements shall be secured as per approved MSRA and manufacturer/project requirements before movement.','Vehicle reversing and unloading activities shall be controlled by competent banksmen with exclusion zones maintained.','Materials and precast elements shall not be stored in undesignated areas or live traffic routes.','Routine logistics inspections shall verify that man-machine interface controls remain effective.','Drivers, banksmen and supervisors shall be briefed on project traffic management and load securing requirements.'],legal:['ADOSH-SF CoP 44.0 - Traffic Management and Logistics','ADOSH-SF CoP 42.0 - Pre Cast Construction','ADOSH-SF CoP 34.0 - Safe Use of Lifting Equipment and Lifting Accessories','ADOSH-SF CoP 36.0 - Plant and Equipment','Aldar OSH MS Rev-08','Project Approved OSH Plan']},
'Housekeeping / Waste Management':{root:'Poor supervision / Housekeeping failure',desc:['Poor housekeeping was observed, including construction debris, waste bags, loose materials and blocked access routes inside villas, around workstations and near excavation areas.','Waste accumulation created slip, trip, fire and access-related risks and affected safe movement during normal and emergency conditions.'],imm:['The affected area was instructed to be cleaned immediately and access routes were cleared from waste and loose materials.','Work was held where housekeeping conditions created unsafe access or trip hazards.','The responsible supervision team was instructed to establish waste collection arrangements without delay.'],act:['Post-shift housekeeping shall be implemented and made part of work completion and PTW closeout requirements.','Waste collection points shall be provided for each villa or work area, and waste shall be removed routinely.','Access routes, emergency routes and work fronts shall remain clear and free from debris, waste and loose materials.','Subcontractors shall be trained to remove waste from workstations at the end of each shift.','No waste bag, no PTW principle shall be applied where housekeeping arrangements are repeatedly poor.','Routine housekeeping inspections shall be conducted and repeated failures escalated to contractor management.'],legal:['ADOSH-SF CoP 54.0 - Waste Management','ADOSH-SF CoP 8.0 - General Workplace Amenities','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA']},
'PPE':{root:'Poor supervision / Lack of enforcement',desc:['Workers were observed carrying out activities without mandatory PPE or task-specific PPE required by the approved MSRA.','Portable power tools and work activities were observed without appropriate eye, face, hand or hearing protection.'],imm:['Workers without mandatory or task-specific PPE were stopped from continuing the activity until correct PPE was provided.','The responsible supervisor was instructed to verify PPE compliance before allowing work to continue.'],act:['All workers shall be provided with mandatory and task-specific PPE in accordance with the approved MSRA and task requirements.','Supervisors shall verify PPE compliance before and during work activities.','Workers shall be trained on correct use, maintenance and storage of PPE.','Routine inspections shall be conducted to identify and correct PPE non-compliance.','Enforcement or disciplinary action shall be implemented for repeated PPE violations.'],legal:['ADOSH-SF CoP 2.0 - Personal Protective Equipment','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA']},
'Leadership / Supervision':{root:'Leadership failure / Poor subcontractor control',desc:['It was evident that engagement of construction managers, project engineers and non-OHS staff during the planned site walk was minimal or absent.','Main contractor and subcontractor supervision failed to identify, stop or escalate unsafe activities occurring at site.','The condition reflects poor planning, weak subcontractor control, lack of leadership presence and ineffective supervision.'],imm:['The unsafe activity was escalated immediately to contractor management for corrective action and accountability.','Responsible supervisors, engineers and HSE personnel were instructed to attend the location and confirm immediate controls.'],act:['Construction managers, project engineers, supervisors and HSE personnel shall ensure active leadership presence during site activities and planned inspections.','All subcontractor activities shall remain under the control and awareness of main contractor management.','Immediate retraining shall be conducted on stop-work authority, PTW field verification, escalation responsibilities and subcontractor control.','A corrective action plan shall be submitted within the required timeframe demonstrating how supervision gaps will be closed.','Enforcement or disciplinary action shall be initiated for repeated absence, failure to stop unsafe work or failure to escalate high-risk conditions.'],legal:['ADOSH-SF CoP 53.0 - OSH Management During Construction Work','Aldar OSH MS Rev-08','OSH Construction Management Plan','Project Approved OSH Plan']},
'Other':{root:'Poor supervision',desc:['Unsafe conditions were observed during the inspection and require immediate corrective and preventive action by the responsible contractor.'],imm:['The unsafe condition was communicated immediately to the responsible site team and temporary control measures were implemented.'],act:['The contractor shall review the unsafe condition, identify the root cause and implement corrective and preventive actions to prevent recurrence.','Closeout evidence shall be submitted and verified by the responsible supervision and OSH team.','Lessons learned shall be communicated to relevant supervisors and workforce.'],legal:['Aldar OSH MS Rev-08','Project Approved OSH Plan','OSH Construction Management Plan']}
};

// Requested category aliases and package/cluster automation
const CATEGORY_ALIASES={
  'Falling Object Protection':'Barricading Hazards / Floor Openings',
  'PTW Field Verification':'Permit to Work',
  'MSRA Quality':'Permit to Work',
  'Lifting/Precast Installation':'Traffic / Logistics / Precast',
  'Traffic &man-Machine Interface':'Traffic / Logistics / Precast',
  'Welfare Arrangement':'Access and Egress',
  'Fire Readiness':'Material Storage / Fire Protection',
  'supervision& Subcontractor Control':'Leadership / Supervision',
  'Temporary & Tool Safety':'Electrical Safety / Portable Tools'
};
Object.entries(CATEGORY_ALIASES).forEach(([alias,base])=>{ if(!PRESETS[alias] && PRESETS[base]) PRESETS[alias]=JSON.parse(JSON.stringify(PRESETS[base])); });
if(PRESETS['Falling Object Protection']){PRESETS['Falling Object Protection'].root='Poor supervision / Inadequate falling object control';PRESETS['Falling Object Protection'].legal=['ADOSH-SF CoP 23.0 - Working at Heights','ADOSH-SF CoP 22.0 - Barricading of Hazards','ADOSH-SF CoP 2.0 - Personal Protective Equipment','Aldar OSH MS Rev-08','Project Approved OSH Plan'];}
if(PRESETS['PTW Field Verification']) PRESETS['PTW Field Verification'].root='PTW field verification failure';
if(PRESETS['MSRA Quality']) PRESETS['MSRA Quality'].root='Poor MSRA implementation / Inadequate risk assessment';
if(PRESETS['Lifting/Precast Installation']){PRESETS['Lifting/Precast Installation'].root='Poor lifting control / Inadequate precast planning';PRESETS['Lifting/Precast Installation'].legal=['ADOSH-SF CoP 34.0 - Safe Use of Lifting Equipment and Lifting Accessories','ADOSH-SF CoP 42.0 - Pre Cast Construction','ADOSH-SF CoP 36.0 - Plant and Equipment','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'];}
if(PRESETS['Traffic &man-Machine Interface']){PRESETS['Traffic &man-Machine Interface'].root='Poor traffic management / Man-machine interface control failure';PRESETS['Traffic &man-Machine Interface'].legal=['ADOSH-SF CoP 44.0 - Traffic Management and Logistics','ADOSH-SF CoP 36.0 - Plant and Equipment','ADOSH-SF CoP 22.0 - Barricading of Hazards','Aldar OSH MS Rev-08','Project Approved OSH Plan'];}
if(PRESETS['Welfare Arrangement']){PRESETS['Welfare Arrangement'].root='Poor welfare management / Inadequate amenities';PRESETS['Welfare Arrangement'].legal=['ADOSH-SF CoP 8.0 - General Workplace Amenities','Aldar OSH MS Rev-08','Project Approved OSH Plan'];}
if(PRESETS['Fire Readiness']){PRESETS['Fire Readiness'].root='Poor fire readiness / Inadequate emergency arrangements';PRESETS['Fire Readiness'].legal=['ADCD 2018 Fire & Life Safety Code of Practice','ADOSH-SF CoP 28.0 - Hot Work Operations','ADOSH-SF CoP 8.0 - General Workplace Amenities','Aldar OSH MS Rev-08','Project Approved OSH Plan'];}
if(PRESETS['supervision& Subcontractor Control']) PRESETS['supervision& Subcontractor Control'].root='Poor supervision / Poor subcontractor control / Leadership failure';
if(PRESETS['Temporary & Tool Safety']){PRESETS['Temporary & Tool Safety'].root='Poor temporary works and tool safety control';PRESETS['Temporary & Tool Safety'].legal=['ADOSH-SF CoP 35.0 - Portable Power Tools','ADOSH-SF CoP 15.0 - Electrical Safety','ADOSH-SF CoP 43.0 - Temporary Structures','Aldar OSH MS Rev-08','Project Approved OSH Plan'];}
const PACKAGE_CLUSTER_MAP={
  '2':['7A','7B','8A','8B','8C','8D'],
  '3':['3','4','5','6'],
  '4':['1A','1B','2A','2B','2C']
};
function updateClusterAndOwner(card, keep=false){
  const pkg=$('.package',card).value;
  const cluster=$('.cluster',card);
  const old=cluster.value;
  opt(cluster, PACKAGE_CLUSTER_MAP[pkg]||[], 'Select cluster / area');
  if(keep && old && (PACKAGE_CLUSTER_MAP[pkg]||[]).includes(old)) cluster.value=old;
  const owner=$('.actionOwner',card);
  if(pkg==='3') owner.value='Innovo';
  if(pkg==='2'||pkg==='4') owner.value='TAJV';
  updateArea(card);
}

const CATEGORIES=Object.keys(PRESETS);const packages=[{value:'2',label:'Package 02'},{value:'3',label:'Package 03'},{value:'4',label:'Package 04'}];const roots=['Poor supervision','Poor planning','PTW system failure','Inspection failure','Leadership failure','Poor subcontractor control','Poor housekeeping','Inadequate competence','Inadequate maintenance','Poor logistics planning'];
const statusBox=$('#statusBox'), attendeeRows=$('#attendeeRows'), obsContainer=$('#observationsContainer');
function setStatus(t,err=false){statusBox.textContent=t;statusBox.style.borderColor=err?'#f87171':'#84cc16'}
function opt(sel,arr,ph){sel.innerHTML=ph?`<option value="">${ph}</option>`:'';arr.forEach(x=>{let o=document.createElement('option');o.value=x.value||x;o.textContent=x.label||x;sel.appendChild(o)})}
function unique(a){return [...new Set((a||[]).filter(Boolean))]}
function lines(t){return String(t||'').split(/\n+/).map(x=>x.replace(/^[-•\d.\s]+/,'').trim()).filter(Boolean)}
function numbered(arr){return unique(arr).map((x,i)=>`${i+1}. ${x}`).join('\n')}
function bulleted(arr){return unique(arr).map(x=>`• ${x}`).join('\n')}

// SMART BRIEF TEXT ENGINE
// If the user deletes the auto-filled wording and writes only a few words
// (example: "open DB and poor cable management"), this engine converts it
// into ALDAR/KEO style observation description, immediate action, action required,
// root cause and legal references for the Word report.
function isBriefManualText(text){
  const t=String(text||'').trim();
  if(!t) return false;
  const hasBullets=/[•\n]/.test(t);
  const hasReportStyle=/(it was observed|it has been observed|it was evident|action to be taken|reference photos|legal\/other)/i.test(t);
  return !hasBullets && !hasReportStyle && t.length<=180;
}
function hasAny(t,words){return words.some(w=>t.includes(w));}
function smartRuleFor(text,selectedCategory=''){
  const t=String(text||'').toLowerCase().replace(/\s+/g,' ');
  const cat=String(selectedCategory||'').toLowerCase();
  if(hasAny(t,['db','dbs','distribution board','open db','open dbd','cable','cables','earthing','generator','electrical','power cable','temporary electrical'])) return 'electrical';
  if(hasAny(t,['scaffold','scaffolding','mobile scaffold','ladder','outrigger','green tag','red tag','plank','platform'])) return 'scaffold';
  if(hasAny(t,['excavation','trench','open trench','boundary wall','excavated','manhole','soil collapse'])) return 'excavation';
  if(hasAny(t,['permit','ptw','work permit','no permit','without permit','red flagged','red flag'])) return 'ptw';
  if(hasAny(t,['edge protection','leading edge','toe board','toeboard','guardrail','roof edge','window edge','fall protection'])) return 'edge';
  if(hasAny(t,['access','egress','walkway','pedestrian','blocked access','obstructed','route','access bridge','ramp'])) return 'access';
  if(hasAny(t,['housekeeping','waste','debris','poor housekeeping','material everywhere','garbage'])) return 'housekeeping';
  if(hasAny(t,['fire','extinguisher','smoke','hot work','combustible','chemical','coshh','storage','store','sprinkler'])) return 'fire';
  if(hasAny(t,['lifting','precast','a-frame','a frame','crane','rigging','sling','trailer','panel'])) return 'lifting';
  if(hasAny(t,['traffic','vehicle','man-machine','man machine','banksman','flagman','reversing','road'])) return 'traffic';
  if(hasAny(t,['mewp','plant','equipment','loader','machine','compressor','jackhammer','tool','power tool','grinder'])) return 'plant';
  if(hasAny(t,['ppe','helmet','gloves','goggles','face shield','harness'])) return 'ppe';
  if(hasAny(t,['msra','risk assessment','method statement','ramS'.toLowerCase()])) return 'msra';
  if(cat.includes('electrical')) return 'electrical';
  if(cat.includes('scaffold')||cat.includes('ladder')) return 'scaffold';
  if(cat.includes('excavation')) return 'excavation';
  if(cat.includes('permit')||cat.includes('ptw')) return 'ptw';
  if(cat.includes('edge')) return 'edge';
  if(cat.includes('access')) return 'access';
  if(cat.includes('housekeeping')||cat.includes('waste')) return 'housekeeping';
  if(cat.includes('fire')||cat.includes('storage')) return 'fire';
  if(cat.includes('traffic')||cat.includes('logistics')||cat.includes('precast')) return 'traffic';
  if(cat.includes('plant')||cat.includes('tool')) return 'plant';
  if(cat.includes('ppe')) return 'ppe';
  if(cat.includes('msra')) return 'msra';
  return 'general';
}
const SMART_RULES={
  electrical:{category:'Electrical Safety / Portable Tools',root:'Electrical safety control failure / Poor supervision',legal:['ADOSH-SF CoP 15.0 - Electrical Safety','ADOSH-SF CoP 35.0 - Portable Power Tools','ADOSH-SF CoP 8.0 - General Workplace Amenities','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that electrical distribution boards / temporary electrical arrangements were not properly secured, exposing personnel to electrical hazards and unauthorized access to live electrical components.','Poor cable management was observed, with temporary cables routed or placed in a manner that may create trip hazards, mechanical damage, unsafe power tapping and potential electrical incidents.','The condition indicates inadequate inspection, poor temporary electrical control and insufficient supervision of electrical safety requirements at the work front.'],imm:['Access to the affected electrical area was restricted immediately and the unsafe condition was communicated to the responsible supervisor and electrical team.','The electrical team was instructed to close and secure the DBs, verify cable routing and remove any unsafe electrical arrangement before allowing further use.','Workers were instructed not to use or approach the affected electrical arrangement until it was inspected and made safe by competent electrical personnel.'],act:['All distribution boards shall be kept closed, secured and locked at all times to prevent unauthorized access to electrical components.','A competent electrician shall inspect all DBs, cables, plugs, sockets, earthing arrangements and temporary electrical connections before further use.','All cables shall be properly routed through insulated supports, cable trays, cable ramps or overhead arrangements to prevent trip hazards and mechanical damage.','Damaged, exposed, poorly routed or unprotected cables shall be removed or replaced immediately.','Electrical warning signage and access control shall be provided where temporary electrical systems are installed.','Routine inspection and colour coding / tagging shall be implemented for electrical tools, DBs and temporary cable arrangements.','Supervisors and workers shall be briefed on electrical safety, cable management and reporting of unsafe electrical conditions.']},
  scaffold:{category:'Scaffolding',root:'Scaffolding inspection failure / Inadequate competent supervision',legal:['ADOSH-SF CoP 26.0 - Scaffolding','ADOSH-SF CoP 23.0 - Working at Heights','ADOSH-SF CoP 37.0 - Ladders','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that scaffolding / ladder arrangements were not maintained in a safe condition and did not fully comply with the approved design, manufacturer requirements or project safety standards.','Unsafe conditions such as missing components, unsafe access, loose planks, inadequate guardrails, unstable arrangements or poor tagging may expose workers to fall hazards and scaffold instability.','This indicates ineffective scaffolding inspection, inadequate supervision and poor control of temporary access arrangements.'],imm:['Unsafe scaffold or ladder use was stopped immediately and access to the affected arrangement was restricted.','Workers were removed from the unsafe platform and the responsible scaffolding team / supervision team was instructed to rectify the condition.','The scaffold was instructed to be inspected by a competent scaffolding inspector before being released for use.'],act:['All unsafe scaffolds, ladders or temporary platforms shall be taken out of service immediately until rectified and inspected.','Scaffolds shall be erected, modified and dismantled only by competent scaffolders in line with approved design and manufacturer requirements.','All required components including guardrails, mid rails, toe boards, bracing, base plates, outriggers, access ladders and locking pins shall be installed before use.','A competent scaffolding inspector shall inspect and tag the scaffold after rectification, modification, adverse weather or any condition affecting stability.','Unauthorized modifications and loose plank arrangements shall be removed immediately.','Routine scaffold inspection records shall be maintained, and repeated non-compliances shall be escalated to project management.']},
  excavation:{category:'Excavation',root:'Poor excavation planning / Inadequate barricading control',legal:['ADOSH-SF CoP 29.0 - Excavation Work','ADOSH-SF CoP 22.0 - Barricading of Hazards','ADOSH-SF CoP 17.0 - Safety Signage and Signals','ADOSH-SF CoP 21.0 - Permit to Work Systems','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that excavation / trench areas were not adequately protected with rigid barricades, warning signage and safe access arrangements.','The condition may expose workers and visitors to fall into excavation, edge collapse, falling materials, restricted emergency access and uncontrolled interaction with plant or vehicles.','The observation indicates inadequate excavation planning, poor barricading maintenance and insufficient field verification prior to work.'],imm:['Access to the unsafe excavation area was restricted immediately and personnel were kept away from the excavation edge.','The responsible engineer and HSE team were instructed to provide suitable barricades, warning signage and safe access arrangements without delay.','Any activity near the excavation was stopped until the required controls were verified by competent supervision.'],act:['All excavation areas shall be protected with rigid barricades / hard barriers and clear warning signs.','Safe access and egress shall be provided for all excavation activities before work starts.','Excavation permits shall be issued only after physical verification of barricading, access, edge stability, services and emergency arrangements.','Materials, blocks, equipment and spoil shall be kept away from excavation edges to maintain safe setback distance.','A competent person shall inspect excavations daily and after any change in condition, and inspection records shall be maintained.','Supervision shall ensure continuous monitoring of excavation protection until the excavation is backfilled or permanently protected.']},
  ptw:{category:'Permit to Work',root:'PTW system failure / Lack of field verification',legal:['ADOSH-SF CoP 21.0 - Permit to Work Systems','ADOSH-SF CoP 53.0 - OSH Management During Construction Work','Aldar OSH MS Rev-08','Project Approved OSH Plan','OSH Construction Management Plan','MSRA'],desc:['It has been observed that the activity was being carried out without adequate Permit to Work control or without proper physical verification of the work location.','The permit arrangements did not sufficiently confirm the actual site condition, required supervision, safe access, isolations and task-specific control measures.','This reflects a breakdown in PTW implementation, supervision, work planning and field verification by the responsible team.'],imm:['The activity was stopped immediately and the permit was placed on hold pending full site verification.','The permit issuer, area engineer, HSE team and responsible supervisor were instructed to review the permit status and actual work conditions.','Work was not allowed to resume until the permit conditions, supervision and required controls were physically verified.'],act:['All activities found outside PTW control shall be suspended immediately until a valid permit is issued and approved by authorized personnel after physical site verification.','The PTW system shall remain under the control of the main contractor and permits shall not be signed without field verification.','Incomplete, incorrect or poorly drafted permits shall be cancelled and revalidated only after required controls are implemented.','Roles and responsibilities of permit issuer, receiver, approver and verifier shall be clearly communicated to engineers, supervisors and HSE personnel.','Routine PTW audits shall be conducted to verify permit quality, site controls and closeout evidence.','Repeated PTW non-compliance shall be escalated to project management for enforcement action.']},
  edge:{category:'Edge Protection',root:'Poor supervision / Inadequate fall prevention control',legal:['ADOSH-SF CoP 23.0 - Working at Heights','ADOSH-SF CoP 22.0 - Barricading of Hazards','ADOSH-SF CoP 2.0 - Personal Protective Equipment','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that edge protection / leading edge controls were missing, incomplete, poorly secured or not maintained in accordance with project and legal requirements.','The condition may expose workers to fall from height and may also allow materials to fall from elevated areas where toe boards or secure mesh are not provided.','This indicates poor inspection, inadequate maintenance and insufficient supervision of fall prevention arrangements.'],imm:['Unsafe work near the leading edge was stopped immediately and access to the exposed area was restricted.','The responsible engineer and supervision team were instructed to reinstate complete and secure edge protection before allowing work to continue.','Workers were removed from the affected area until the edge protection system was verified.'],act:['All activities near unprotected leading edges shall be suspended until complete edge protection is installed and verified.','Edge protection shall include compliant top rails, mid rails, toe boards and secure mesh where required.','Edge protection systems shall be properly anchored and maintained to prevent displacement during work activities.','Missing, loose or damaged sections shall be reinstated immediately and checked across the wider work area.','A competent supervisor shall inspect edge protection daily and maintain evidence of closeout.','Workers and supervisors shall be briefed on maintaining fall prevention and falling object controls.']},
  access:{category:'Access and Egress',root:'Poor planning / Poor housekeeping / Poor supervision',legal:['ADOSH-SF CoP 8.0 - General Workplace Amenities','ADOSH-SF CoP 22.0 - Barricading of Hazards','ADOSH-SF CoP 17.0 - Safety Signage and Signals','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that access and egress arrangements were obstructed, poorly maintained or not suitable for safe movement to the work location.','Unsafe access arrangements such as single planks, uneven ramps, blocked routes, debris, cables or material storage may create slip, trip and fall hazards and affect emergency escape.','The condition indicates inadequate planning, housekeeping and supervision of access arrangements.'],imm:['Unsafe access routes were restricted immediately and workers were redirected to safer access points.','The responsible supervision team was instructed to remove obstructions and restore safe access without delay.','Work was held at the affected location where safe access and egress could not be ensured.'],act:['All unsafe and substandard access arrangements shall be removed immediately and replaced with safe access bridges, ramps, stairs or platforms.','Access and egress routes shall be kept clear of materials, cables, debris and protruding steel at all times.','A dedicated team shall be appointed for access installation, inspection and routine maintenance.','Access routes shall be clearly demarcated, provided with suitable signage and inspected daily.','PTW approval shall include physical verification of safe access and housekeeping conditions.','The workforce shall be briefed on maintaining safe access and emergency egress arrangements.']},
  housekeeping:{category:'Housekeeping / Waste Management',root:'Poor housekeeping / Poor supervision',legal:['ADOSH-SF CoP 54.0 - Waste Management','ADOSH-SF CoP 8.0 - General Workplace Amenities','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that housekeeping conditions were not maintained, with waste, debris or materials accumulated in work areas, access routes or near active work fronts.','The condition may create slip, trip and fall hazards, obstruct emergency access and contribute to fire or falling object risks.','This indicates inadequate housekeeping planning, poor supervision and weak control of subcontractor work areas.'],imm:['The responsible team was instructed to remove waste, debris and obstructions immediately from the affected area.','Access routes and work fronts were required to be cleaned and made safe before continuation of work.','Supervision was instructed to verify housekeeping closeout and prevent re-accumulation.'],act:['Waste and debris shall be removed from work fronts and access routes on a routine basis and at the end of each shift.','Dedicated waste collection points shall be provided and maintained for each work area where required.','Materials shall be stored only in designated areas and shall not obstruct access, emergency routes or workstations.','Housekeeping shall be included as part of PTW verification and job completion requirements.','Supervisors shall conduct routine housekeeping inspections and maintain closeout evidence.','Subcontractors shall be briefed and held accountable for maintaining clean and safe work areas.']},
  fire:{category:'Material Storage / Fire Protection',root:'Poor fire readiness / Poor material storage control',legal:['ADCD 2018 Fire & Life Safety Code of Practice','ADOSH-SF CoP 8.0 - General Workplace Amenities','ADOSH-SF CoP 28.0 - Hot Work Operations','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that materials / combustible items / chemicals were stored without adequate fire safety, segregation, access control or emergency readiness arrangements.','Fire protection arrangements such as extinguishers, hose reels, smoke detection, emergency access or fire wardens were not adequately maintained or verified.','The condition may increase fire load, delay emergency response and expose workers and assets to serious fire risk.'],imm:['The unsafe storage or fire readiness deficiency was communicated immediately to the responsible team for correction.','Ignition sources and unsafe storage arrangements were controlled, and the area was reviewed for immediate fire risk.','The contractor was instructed to provide suitable firefighting equipment and access control without delay.'],act:['A fire risk assessment shall be conducted for the affected storage / work area and suitable fire prevention controls shall be implemented.','Combustible materials and chemicals shall be stored only in designated, segregated and controlled storage areas.','Adequate firefighting equipment, inspection records, emergency contacts and access routes shall be maintained at all times.','Fire wardens shall be appointed for routine inspection and emergency readiness verification.','Materials shall be stacked safely below sprinkler height and clear of emergency routes.','Workers and supervisors shall be briefed on fire prevention, storage control and emergency response requirements.']},
  lifting:{category:'Lifting/Precast Installation',root:'Poor lifting/precast control / Inadequate planning',legal:['ADOSH-SF CoP 34.0 - Safe Use of Lifting Equipment and Lifting Accessories','ADOSH-SF CoP 42.0 - Pre Cast Construction','ADOSH-SF CoP 36.0 - Plant and Equipment','ADOSH-SF CoP 44.0 - Traffic Management and Logistics','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that lifting / precast handling or installation arrangements were not adequately controlled in line with the approved lifting plan and project requirements.','The condition may expose workers to falling loads, unstable precast elements, unsafe trailer movement, inadequate exclusion zones or poor load securing arrangements.','This indicates inadequate planning, supervision and verification of lifting / precast installation controls.'],imm:['Unsafe lifting / precast activity was stopped immediately and the lifting area was controlled.','Personnel were removed from the lifting zone and the lifting supervisor / responsible engineer was instructed to verify the lifting arrangement.','The activity was not allowed to continue until the lifting plan, equipment certification, rigging and exclusion zone were confirmed.'],act:['All lifting and precast installation activities shall be carried out under an approved lifting plan and competent supervision.','Lifting equipment, accessories, A-frame arrangements, trailers and load securing methods shall be inspected and verified before use.','Exclusion zones shall be established and maintained during lifting and precast installation.','Each precast element shall be secured as per approved method statement and manufacturer requirements.','Banksman / flagman arrangements and traffic controls shall be provided where plant or trailers are moving.','Workers and supervisors shall be briefed on lifting, load control and exclusion zone requirements.']},
  traffic:{category:'Traffic &man-Machine Interface',root:'Poor traffic management / Man-machine interface failure',legal:['ADOSH-SF CoP 44.0 - Traffic Management and Logistics','ADOSH-SF CoP 33.0 - Working On or Adjacent to a Road','ADOSH-SF CoP 36.0 - Plant and Equipment','ADOSH-SF CoP 22.0 - Barricading of Hazards','Aldar OSH MS Rev-08','Project Approved OSH Plan'],desc:['It has been observed that traffic / logistics or man-machine interface arrangements were not adequately controlled within the work area.','Unsafe interaction between pedestrians, vehicles, plant, trailers or live roads may expose personnel to struck-by, reversing, blind spot and uncontrolled movement hazards.','The condition indicates inadequate traffic planning, segregation, signage and supervision of plant / vehicle movement.'],imm:['The unsafe traffic movement or man-machine interface condition was controlled immediately and the affected route was restricted.','Plant / vehicle movement was held until suitable segregation, signage, banksman control and safe pedestrian routes were confirmed.','The logistics and supervision team were instructed to rectify the traffic control arrangement without delay.'],act:['Traffic management arrangements shall be planned and maintained, including pedestrian segregation, signage, speed control, lighting and banksman arrangements.','Plant and vehicle operators shall follow approved routes and shall not operate in uncontrolled pedestrian or work zones.','Safe pedestrian access shall be provided and maintained in all active work areas.','Reversing activities shall be controlled by competent banksman / flagman where required.','Routine logistics inspections shall verify that man-machine interface controls remain effective.','The workforce and drivers shall be briefed on traffic routes, blind spots and site movement rules.']},
  plant:{category:'Plant and Equipment',root:'Poor equipment inspection / Inadequate maintenance',legal:['ADOSH-SF CoP 36.0 - Plant and Equipment','ADOSH-SF CoP 35.0 - Portable Power Tools','ADOSH-SF CoP 15.0 - Electrical Safety','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that plant, equipment or portable tools were not adequately inspected, maintained or controlled before use.','Defective equipment, damaged tools, missing inspection evidence, unsafe attachments or poor emergency arrangements may expose workers to mechanical, electrical, fire or operational hazards.','The condition indicates inadequate pre-use inspection, poor maintenance control and insufficient supervision of plant and equipment safety.'],imm:['Unsafe plant, equipment or tools were removed from use immediately pending inspection and rectification.','The responsible supervisor / competent person was instructed to verify the equipment condition, certification and emergency arrangements before further use.','Workers were instructed not to operate defective or uninspected equipment.'],act:['All plant, equipment and portable tools shall be inspected by competent personnel before use and maintained in safe condition.','Defective, damaged, modified or uninspected equipment shall be removed from service immediately.','Pre-use inspection checklists, third-party certificates, inspection stickers and colour coding shall be maintained where applicable.','Emergency arrangements such as extinguishers, stop buttons, guards and access control shall be provided and checked.','Operators and workers shall be trained on safe operation, inspection and defect reporting requirements.','Routine monitoring shall be implemented by the supervision and HSE team to prevent recurrence.']},
  ppe:{category:'PPE',root:'Poor PPE compliance / Poor supervision',legal:['ADOSH-SF CoP 2.0 - Personal Protective Equipment','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that personnel were carrying out work without mandatory PPE or task-specific PPE required by the approved MSRA.','The absence of suitable PPE may expose workers to injury from impact, cuts, dust, flying particles, electrical hazards or fall-related risks depending on the activity.','This indicates inadequate supervision, weak enforcement and insufficient awareness of PPE requirements.'],imm:['Personnel not complying with PPE requirements were stopped and instructed to correct the unsafe condition immediately.','The responsible supervisor was instructed to ensure mandatory and task-specific PPE is provided before work continues.','Workers were reminded not to continue the activity without the required PPE.'],act:['Mandatory and task-specific PPE shall be provided and used as per the approved MSRA and site requirements.','Supervisors shall verify PPE compliance before and during the activity.','Workers shall be trained on correct PPE use, storage, maintenance and limitations.','Routine inspections shall be conducted to monitor compliance.','Repeated PPE violations shall be subject to enforcement action in line with project procedures.']},
  msra:{category:'MSRA Quality',root:'Poor MSRA implementation / Inadequate risk assessment',legal:['ADOSH-SF CoP 53.0 - OSH Management During Construction Work','ADOSH-SF CoP 53.1 - OSH Construction Management Plan','Aldar OSH MS Rev-08','Project Approved OSH Plan','MSRA'],desc:['It has been observed that the approved MSRA / task risk assessment did not adequately reflect the actual site condition or required controls at the work front.','The workforce and supervision did not demonstrate adequate understanding or implementation of the method statement and risk assessment requirements.','This indicates poor MSRA quality, weak communication and inadequate field verification of control measures.'],imm:['The activity was paused until the MSRA and actual site controls were reviewed by the responsible engineer and HSE team.','The supervisor was instructed to brief the workforce on task-specific hazards and required control measures.','Work was not allowed to continue until the required MSRA controls were implemented at the work front.'],act:['The MSRA shall be reviewed and updated to reflect actual site conditions, task sequence, hazards and control measures.','Supervisors shall conduct toolbox talks and communicate MSRA requirements to all involved workers before work starts.','Field verification shall be conducted to ensure that approved control measures are implemented at the work front.','Any change in site condition, work method or sequence shall trigger MSRA review before work continues.','The Construction Manager and HSE team shall monitor MSRA implementation and maintain evidence of briefing and compliance.']},
  general:{category:'Other',root:'Poor supervision / Planning and control failure',legal:['Aldar OSH MS Rev-08','Project Approved OSH Plan','OSH Construction Management Plan','MSRA'],desc:['It has been observed that an unsafe condition was present at the work location and required immediate corrective and preventive action.','The condition may expose workers, visitors or site assets to unacceptable risk if not controlled in a timely manner.','This indicates inadequate planning, supervision and monitoring of site safety requirements.'],imm:['The unsafe condition was communicated immediately to the responsible site team and temporary controls were implemented.','The affected activity or area was placed under control until suitable corrective measures were agreed and verified.','The responsible supervision team was instructed to rectify the issue without delay.'],act:['The contractor shall review the unsafe condition, identify the root cause and implement corrective and preventive actions to avoid recurrence.','The responsible management team shall verify closeout evidence and communicate lessons learned to relevant supervisors and workforce.','Routine inspection and monitoring shall be strengthened to ensure similar issues are identified and corrected early.','Supervision shall ensure project OSH requirements are implemented across the work area, not only at the specific observation location.']}
};
function smartExpandFromBrief(text,selectedCategory=''){
  const rule=SMART_RULES[smartRuleFor(text,selectedCategory)]||SMART_RULES.general;
  return JSON.parse(JSON.stringify(rule));
}
function applySmartBriefToCard(card){
  const descEl=$('.observationDescription',card), immEl=$('.immediateAction',card), actEl=$('.preventiveAction',card), catEl=$('.observationCategory',card), rootEl=$('.rootCause',card);
  const brief=descEl.value.trim();
  if(!isBriefManualText(brief)){setStatus('Smart wording works best when the Observation Description has only a few words.',true);return;}
  const smart=smartExpandFromBrief(brief,catEl.value);
  if(!catEl.value || catEl.value==='Other') catEl.value=smart.category;
  rootEl.value=smart.root;
  descEl.value=bulleted(smart.desc);
  immEl.value=bulleted(smart.imm);
  actEl.value=numbered(smart.act);
  $$('.legalGrid input',card).forEach(x=>x.checked=(smart.legal||[]).includes(x.value));
  setStatus('Smart ALDAR wording created from your short text.');
}
function enrichObservation(o){
  if(!isBriefManualText(o.desc)) return o;
  const smart=smartExpandFromBrief(o.desc,o.category);
  return {...o, category:(!o.category||o.category==='Other')?smart.category:o.category, root:o.root||smart.root, desc:bulleted(smart.desc), immediate:o.immediate||bulleted(smart.imm), actions:o.actions||numbered(smart.act), legal:(o.legal&&o.legal.length)?o.legal:smart.legal};
}

function fillPick(sel,arr,ph){opt(sel,arr,ph)}
function chips(el,arr,ta,replace=false){el.innerHTML='';unique(arr).forEach((x,i)=>{let b=document.createElement('button');b.type='button';b.className='chip';b.textContent=(i+1)+'. '+(x.length>80?x.slice(0,80)+'...':x);b.title=x;b.onclick=()=>{ta.value=replace?x:(ta.value.trim()?ta.value.trim()+'\n'+x:x)};el.appendChild(b)})}
function addAttendee(seed={}){let f=$('#attendeeTpl').content.cloneNode(true);attendeeRows.appendChild(f);let r=attendeeRows.lastElementChild;$('.attendeeName',r).value=seed.name||'';$('.attendeeDesignation',r).value=seed.designation||'';$('.attendeeEntity',r).value=seed.entity||'KEO';$('.remove',r).onclick=()=>{if($$('#attendeeRows tr').length>1)r.remove();else setStatus('At least one attendee is required.',true)}}
function legalGrid(card){let g=$('.legalGrid',card);g.innerHTML='';LEGAL.forEach(ref=>{let l=document.createElement('label');l.className='legalPill';l.innerHTML=`<input type="checkbox" value="${ref}"><span>${ref}</span>`;g.appendChild(l)})}
function clusterText(v){v=String(v||'').trim();return v?(v.toLowerCase().startsWith('cluster')?v:'Cluster '+v):''}
function updateArea(card){let t=['Package '+($('.package',card).value||'-'),clusterText($('.cluster',card).value)||'-',$('.villaNo',card).value?`Villa ${$('.villaNo',card).value}`:'-'].join(' - ');$('.areaPreview',card).textContent='Area: '+t}
function apply(card,replace=true){let key=$('.observationCategory',card).value||'Other',p=PRESETS[key]||PRESETS.Other;fillPick($('.descriptionPick',card),p.desc,'Select description');fillPick($('.immediatePick',card),p.imm,'Select immediate action');fillPick($('.actionPick',card),p.act,'Select action');chips($('.descriptionChips',card),p.desc,$('.observationDescription',card),true);chips($('.immediateChips',card),p.imm,$('.immediateAction',card));chips($('.actionChips',card),p.act,$('.preventiveAction',card));if(replace){$('.rootCause',card).value=p.root||'';$('.observationDescription',card).value=bulleted(p.desc);$('.immediateAction',card).value=bulleted(p.imm);$('.preventiveAction',card).value=numbered(p.act)}let set=new Set(p.legal||[]);$$('.legalGrid input',card).forEach(c=>c.checked=set.has(c.value));updateArea(card)}
function addObservation(seed={}){let f=$('#observationTpl').content.cloneNode(true);obsContainer.appendChild(f);let card=obsContainer.lastElementChild;opt($('.package',card),packages,'Select package');opt($('.observationCategory',card),CATEGORIES,'Select category');opt($('.rootCause',card),roots,'Select root cause');legalGrid(card);$('.package',card).onchange=()=>updateClusterAndOwner(card);$('.cluster',card).onchange=()=>updateArea(card);$('.villaNo',card).oninput=()=>updateArea(card);$('.observationCategory',card).onchange=()=>apply(card,true);$('.autofill',card).onclick=()=>apply(card,true);$('.smartImprove',card).onclick=()=>applySmartBriefToCard(card);$('.descriptionPick',card).onchange=e=>{$('.observationDescription',card).value=e.target.value};$('.immediatePick',card).onchange=e=>{$('.immediateAction',card).value=$('.immediateAction',card).value.trim()?$('.immediateAction',card).value.trim()+'\n'+e.target.value:e.target.value};$('.actionPick',card).onchange=e=>{$('.preventiveAction',card).value=$('.preventiveAction',card).value.trim()?$('.preventiveAction',card).value.trim()+'\n'+e.target.value:e.target.value};$('.removeObs',card).onclick=()=>{if($$('.obsCard').length>1){card.remove();renum()}else setStatus('At least one observation is required.',true)};$('.selectAllLegal',card).onclick=()=>$$('.legalGrid input',card).forEach(x=>x.checked=true);$('.clearLegal',card).onclick=()=>$$('.legalGrid input',card).forEach(x=>x.checked=false);$('.evidencePhotos',card).onchange=e=>{let p=$('.photoPreview',card);p.innerHTML='';[...e.target.files].forEach(file=>{let r=new FileReader();r.onload=ev=>{let img=document.createElement('img');img.src=ev.target.result;p.appendChild(img)};r.readAsDataURL(file)})};Object.entries(seed).forEach(([k,v])=>{let n=$('.'+k,card);if(n)n.value=v});updateClusterAndOwner(card,true);if(!seed.observationCategory)$('.observationCategory',card).value='Access and Egress';apply(card,!seed.observationDescription);renum()}
function renum(){$$('.obsCard').forEach((c,i)=>$('.obsNo',c).textContent=i+1)}
function getData(){return{projectTitle:$('#projectTitle').value.trim(),date:$('#inspectionDate').value,time:$('#inspectionTime').value,ref:$('#referenceNo').value.trim(),attendees:$$('#attendeeRows tr').map(r=>({name:$('.attendeeName',r).value.trim(),designation:$('.attendeeDesignation',r).value.trim(),entity:$('.attendeeEntity',r).value})).filter(x=>x.name||x.designation),observations:$$('.obsCard').map((c,i)=>({no:i+1,package:$('.package',c).value,cluster:$('.cluster',c).value.trim(),villa:$('.villaNo',c).value.trim(),category:$('.observationCategory',c).value,risk:$('.riskCategory',c).value,response:$('.responseCategory',c).value,owner:$('.actionOwner',c).value,root:$('.rootCause',c).value,closed:$('.dateClosed',c).value,desc:$('.observationDescription',c).value.trim(),immediate:$('.immediateAction',c).value.trim(),actions:$('.preventiveAction',c).value.trim(),legal:$$('.legalGrid input',c).filter(x=>x.checked).map(x=>x.value).concat($('.legalCustom',c).value.trim()?[$('.legalCustom',c).value.trim()]:[]),photos:[...$('.evidencePhotos',c).files]}))}}
function fmtDate(d){if(!d)return'';let [y,m,day]=d.split('-');return `${day}.${m}.${y}`}function fmtTime(t){if(!t)return'';let [h,m]=t.split(':').map(Number);let ap=h>=12?'PM':'AM';h=h%12||12;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')} ${ap}`}
function validate(d){if(!d.projectTitle)return'Project title is required.';if(!d.date)return'Date is required.';if(!d.ref)return'Reference number is required.';if(!d.attendees.length)return'At least one attendee is required.';for(let o of d.observations){if(!o.package)return`Observation ${o.no}: package is required.`;if(!o.category)return`Observation ${o.no}: category is required.`;if(!o.desc)return`Observation ${o.no}: description is required.`;if(!o.actions)return`Observation ${o.no}: action required is required.`}return''}
async function arrBuf(file){return await file.arrayBuffer()}async function urlBuf(url){let r=await fetch(url);return await r.arrayBuffer()}
function para(text,opt={}){const {Paragraph,TextRun,AlignmentType}=docx;return new Paragraph({alignment:opt.center?AlignmentType.CENTER:undefined,spacing:{after:0,before:0,line:240},children:[new TextRun({text:String(text||' '),bold:!!opt.bold,font:'Poppins',size:opt.size||21,color:opt.color||'000000'})]})}
function cell(children,opt={}){const {TableCell,WidthType}=docx;return new TableCell({width:opt.width?{size:opt.width,type:WidthType.PERCENTAGE}:undefined,shading:opt.shade?{fill:'D9D9D9'}:undefined,borders:border,children:Array.isArray(children)?children:[children]})}
function textLines(text){return lines(text).map(x=>para(x))}
let border={top:{style:'single',size:6,color:'000000'},bottom:{style:'single',size:6,color:'000000'},left:{style:'single',size:6,color:'000000'},right:{style:'single',size:6,color:'000000'}};
async function generateWord(){try{const d=getData();d.observations=d.observations.map(enrichObservation);const err=validate(d);if(err){setStatus(err,true);return}const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,AlignmentType,Footer,ImageRun}=docx;let logo=await urlBuf('aldar.png');let attendeeRowsDoc=[new TableRow({children:[cell(para('Name',{bold:true,center:true}),{shade:true}),cell(para('Designation',{bold:true,center:true}),{shade:true}),cell(para('Entity',{bold:true,center:true}),{shade:true})]})];d.attendees.forEach(a=>attendeeRowsDoc.push(new TableRow({children:[cell(para(a.name,{center:true})),cell(para(a.designation,{center:true})),cell(para(a.entity,{center:true}))]})));let attendeesTable=new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:attendeeRowsDoc});let responseTable=new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[cell(para('Response Category',{bold:true,center:true}),{shade:true,width:22}),cell(para('Definition',{bold:true,center:true}),{shade:true,width:78})]}),...['A|An issue requiring immediate action to eliminate or reduce high risk','B|An issue requiring action within 24 hours to eliminate or reduce risk','C|An issue requiring action within 3 days to eliminate or reduce risk','D|An issue requiring action to meet best practice and continually improve standards at the site, with agreed timelines.'].map(x=>{let [a,b]=x.split('|');return new TableRow({children:[cell(para(a,{bold:true,center:true})),cell(para(b))]})})]});
let obsRows=[new TableRow({children:[cell(para('No.',{bold:true,center:true}),{shade:true,width:6}),cell(para('Observation',{bold:true,center:true}),{shade:true,width:64}),cell(para('By\nWhom',{bold:true,center:true}),{shade:true,width:10}),cell(para('Category',{bold:true,center:true}),{shade:true,width:8}),cell(para('Date\nClosed',{bold:true,center:true}),{shade:true,width:10})]})];let photoNo=1,allPhotos=[];for(let o of d.observations){let pars=[];pars.push(para(`Observation Category: ${o.category}`,{bold:true}));pars.push(para(`Risk Category: ${o.risk}`,{bold:true}));let area=[o.package?`Package ${o.package}`:'',clusterText(o.cluster),o.villa?`Villa ${o.villa}`:''].filter(Boolean).join(' - ');pars.push(para(`Area: ${area}`,{bold:true}));if(o.root)pars.push(para(`Likely Root Cause: ${o.root}`,{bold:true}));pars.push(para('Observation Description:',{bold:true}));pars.push(...textLines(o.desc));if(o.immediate){pars.push(para('Immediate Action Taken:',{bold:true}));pars.push(...textLines(o.immediate))}pars.push(para('Action to be taken as agreed, but not limited to:',{bold:true}));pars.push(...textLines(o.actions));if(o.photos.length){let start=photoNo,end=photoNo+o.photos.length-1;pars.push(para(start===end?`Reference photo ${String(start).padStart(2,'0')}`:`Reference photos ${String(start).padStart(2,'0')} to ${String(end).padStart(2,'0')}`,{bold:true}));photoNo=end+1;o.photos.forEach(p=>allPhotos.push(p))}if(o.legal.length){pars.push(para('Legal/other Requirements:',{bold:true}));o.legal.forEach(l=>pars.push(para(l)))}obsRows.push(new TableRow({children:[cell(para(o.no,{center:true})),cell(pars),cell(para(o.owner,{center:true})),cell(para(o.response,{bold:true,center:true})),cell(para(fmtDate(o.closed),{center:true}))]}))}
let obsTable=new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:obsRows});let photoRows=[];let slots=Math.max(allPhotos.length,6);for(let i=0;i<slots;i+=3){let caps=[],imgs=[];for(let j=0;j<3;j++){let idx=i+j;caps.push(cell(para(`Photo ${String(idx+1).padStart(2,'0')}`,{bold:true,center:true})));if(allPhotos[idx]){let buf=await arrBuf(allPhotos[idx]);imgs.push(cell(new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({data:buf,transformation:{width:205,height:205}})]}))) }else imgs.push(cell([para(' '),para(' '),para(' ')]))}photoRows.push(new TableRow({children:caps}),new TableRow({children:imgs}))}let photosTable=new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:photoRows});let introArea=d.observations.map(o=>[o.package?`Package ${o.package}`:'',clusterText(o.cluster),o.villa?`Villa ${o.villa}`:''].filter(Boolean).join(' - ')).filter(Boolean)[0]||d.projectTitle;let doc=new Document({sections:[{properties:{page:{margin:{top:650,right:650,bottom:650,left:650}}},footers:{default:new Footer({children:[para('ALDAR OSH-MS Rev 08/ May-2025                              Appendix 13',{size:18})]})},children:[new Paragraph({alignment:AlignmentType.LEFT,children:[new ImageRun({data:logo,transformation:{width:74,height:74}})]}),para('OSH Inspection Report',{bold:true,center:true,size:30}),para(`Project Title: ${d.projectTitle}`,{bold:true}),new Paragraph({children:[new TextRun({text:`Date: ${fmtDate(d.date)}`,bold:true,font:'Poppins',size:21}),new TextRun({text:'                                             ',font:'Poppins',size:21}),new TextRun({text:`Time: ${fmtTime(d.time)}`,bold:true,font:'Poppins',size:21})]}),para(`Reference No: ${d.ref}`,{bold:true}),para('Attendees:',{bold:true}),attendeesTable,para(' '),responseTable,para(' '),para(`An OSH Inspection was carried out at ${introArea} on ${fmtDate(d.date)}. KEO International Consultants and contractor representatives were present during the OSH Site Inspection, and the following observations have been highlighted by KEO and appropriate actions should be taken by all the parties involved according to the response category and across the whole project.`),para('Observations:',{bold:true}),obsTable,para('Evidence photographs',{bold:true}),photosTable]}]});let blob=await Packer.toBlob(doc);let [y,m,day]=d.date.split('-');saveAs(blob,`ALDAR Projects OSH Inspection Report- ${d.ref}- ${day}-${m}-${y}_.docx`);setStatus('Final ALDAR Word file generated successfully.')}catch(e){console.error(e);setStatus('Error: '+e.message,true)}}
$('#addAttendeeBtn').onclick=()=>addAttendee();$('#addObservationBtn').onclick=()=>addObservation();$('#generateDocBtn').onclick=generateWord;
[
  {name:'Ugochukwu Godwin',designation:'OHS Manager',entity:'KEO'},
  {name:'Javed Iqbal',designation:'OSH Engineer',entity:'KEO'},
  {name:'Subbian Samraj',designation:'OHS Engineer',entity:'KEO'},
  {name:'Shakir Khan',designation:'OHS Engineer',entity:'KEO'},
  {name:'Shinoj M Chandran',designation:'OHS Officer',entity:'KEO'},
  {name:'Jackson Rodriguez',designation:'Safety Officer',entity:'KEO'},
  {name:'Abdelmonem Hussein',designation:'OSH Officer',entity:'KEO'}
].forEach(addAttendee);
addObservation();
